### ISSUE TITLE
Warning: Undefined array key "tl_class"

### ISSUE THREAD

**Issue by bennyborn** [postyou/contao-proven-expert#1]
The line https://github.com/postyou/contao-proven-expert/blob/1d62737de9ec7d76a3bc134cf4cc4284b7ead6c1/contao/dca/tl_module.php#L44 should be changed to

```php
$GLOBALS['TL_DCA']['tl_module']['fields']['html']['eval']['tl_class'] = ($GLOBALS['TL_DCA']['tl_module']['fields']['html']['eval']['tl_class']??'') . ' clr';
```

**Comment by MarkejN** [comment]
Thanks for reporting. The line is no longer needed. I removed it in [1.0.3](https://github.com/postyou/contao-proven-expert/releases/tag/1.0.3).
